# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build.

on:
  push:
    branches: [ "development" ] 
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RELEASE_CYCLE: "25MR2"

jobs:
    create-artifact:
        name: Creates the artifact
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create artifact
          uses: actions/upload-artifact@v4
          with:
            name: Artifact
            path: ./
            if-no-files-found: error
            retention-days: 1
            compression-level: 0
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: create-artifact
        env:
            TEST: ${{ vars.STAGING_VAR }}
        environment:
            name: staging
            url: https://www.google.com
        steps:
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: Artifact

            - name: deploy
              run: |
                 echo "Deployed"

  
