name: Build.

on:
  workflow_call:
    inputs:
      RELEASE_CYCLE:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string

jobs:
    create-artifact:
        name: Creates the artifact
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create artifact
          uses: actions/upload-artifact@v4
          with:
            name: Artifact
            path: ./
            if-no-files-found: error
            retention-days: 1
            compression-level: 0
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: create-artifact
        environment:
            name: ${{ inputs.ENVIRONMENT }}
            url: https://www.google.com
        steps:
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: Artifact

            - name: deploy
              run: |
                 echo "Deployed version ${{ inputs.RELEASE_CYCLE }}" 

  
