name: Update Release Cycle
on:
  pull_request:
    types:
      - closed
    branches:
      - development

jobs:
  check-merged:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged
        id: check_merge
        if: github.event.pull_request.merged == true
        run: |
          echo "Pull-request was merged, action will run..."
  update-release-cycle:
    needs: check-merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.GH_WF_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_WF_TOKEN }}
          branch: release/development-to-staging
          base: staging
          title: "Development --> Staging"
          labels: "Promote,Staging"
          draft: "always-true"
